[workspace]

resolver = "2"

members = [
    "metric-collector",
    "example-application",
    "poc", "percentile-ps"
]

exclude = ["benchmarks/goose", "benchmarks/goose-test", "benchmarks/kafka/scrape-cc2023-producer"]
