[workspace]

resolver = "2"

members = [
    "metric-collector",
]

exclude = [
    "misc", 
    "artifacts/paper-1/benchmarks/kafka/scrape-experiment-producer", 
    "artifcats/paper-1/benchmarks/dependencies/goose", 
    "artifcats/paper-1/benchmarks/dependencies/solr-benchmark", 
    "artifcats/paper-1/benchmarks/kafka/scrape-cc2023-producer"
]
