apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: sample
spec:
  replicas: {{ .Values.clickhouse.keeperReplicas}} 
  dataVolumeClaimSpec:
    storageClassName: {{ .Values.clickhouse.storageClassName }}
    resources:
      requests:
        storage: {{ .Values.clickhouse.keeperStorage }}
---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: sample
spec:
  replicas: {{ .Values.clickhouse.clickhouseReplicas }}
  shards: {{ .Values.clickhouse.clickhouseShards }} 
  dataVolumeClaimSpec:
    storageClassName: {{ .Values.clickhouse.storageClassName }}
    resources:
      requests:
        storage: {{ .Values.clickhouse.clickhouseStorage }}
  settings:
    defaultUserPassword:
      secret:
        key: password
        name: default-password
    logger:
      level: information
    extraUsersConfig:
      profiles:
        default:
          join_use_nulls: 1
          distributed_product_mode: "global"
          optimize_skip_unused_shards: 1
      users:
        reader:
          password_sha256_hex: {{ .Values.clickhouse.readerPassword }}
          profile: default
          grants:
            - query: "GRANT SELECT ON *.*"
  keeperClusterRef:
    name: sample
---
apiVersion: v1
kind: Secret
metadata:
  name: default-password
data:
  password: {{ .Values.clickhouse.defaultUserPassword }}
