/* automatically generated by rust-bindgen 0.71.1 */

pub const __BITS_PER_LONG: u32 = 64;
pub const __BITS_PER_LONG_LONG: u32 = 64;
pub const MAX_ENTRIES: u32 = 8192;
pub const SAMPLE_MAX_ENTRIES: u32 = 8192;
pub const PENDING_MAX_ENTRIES: u32 = 8192;
pub const SAMPLES: u32 = 10;
pub type __s8 = ::std::os::raw::c_schar;
pub type __u8 = ::std::os::raw::c_uchar;
pub type __s16 = ::std::os::raw::c_short;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __s64 = ::std::os::raw::c_longlong;
pub type __u64 = ::std::os::raw::c_ulonglong;
pub const truth: __u8 = 1;
pub const z64: __u64 = 0;
pub const z32: __u32 = 0;
